### ISSUE TITLE
tests failing with python 3.7.0

### ISSUE THREAD

**Issue by dvzrv** [erikrose/nose-progressive#90]
I'm currently tring to ship this as a package on Arch Linux [community].
However I'm unable to get the tests to run:

```
/usr/lib/python3.7/site-packages/nose/plugins/manager.py:395: RuntimeWarning: Unable to load plugin noseprogressive = noseprogressive:ProgressivePlugin: No module named '__builtin__'                                                                                                                                        
  RuntimeWarning)
E
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named '__builtin__')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/build/python-nose-progressive/src/python-nose-progressive-1.5.1/noseprogressive/__init__.py", line 1, in <module>
    from noseprogressive.plugin import ProgressivePlugin
  File "/build/python-nose-progressive/src/python-nose-progressive-1.5.1/noseprogressive/plugin.py", line 11, in <module>
    from noseprogressive.wrapping import cmdloop, set_trace, StreamWrapper
  File "/build/python-nose-progressive/src/python-nose-progressive-1.5.1/noseprogressive/wrapping.py", line 4, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

Any help would be greatly appreciated!

**Comment by erikrose** [comment]
This may also be what's blocking me from doing a new release. It's to do with some tests not passing, at any rate.

**Comment by dvzrv** [comment]
Ah, seems I was using the test wrong. I'm now exporting the `build/lib` dir to `$PYTHONPATH` correctly (as I'm creating a system package this happens after build, but before installation), but now I'm still getting:

```
...............E....
======================================================================
ERROR: The logcapture plugin formats errors by extracting and converting
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python-nose-progressive/src/python-nose-progressive-1.5.2/noseprogressive/tests/test_tracebacks.py", line 107, in test_proxied_syntax_error
    ''.join(format_traceback(*proxied_syntax_tb))
  File "/build/python-nose-progressive/src/python-nose-progressive-1.5.2/build/lib/noseprogressive/tracebacks.py", line 89, in format_traceback
    formatted_exception = format_exception_only(SyntaxError, exc_value)
  File "/usr/lib/python3.7/traceback.py", line 140, in format_exception_only
    return list(TracebackException(etype, value, None).format_exception_only())
  File "/usr/lib/python3.7/traceback.py", line 515, in __init__
    self.filename = exc_value.filename
AttributeError: 'SyntaxError' object has no attribute 'filename'

----------------------------------------------------------------------
Ran 20 tests in 0.104s

FAILED (errors=1)
```

Any thoughts?

**Comment by dvzrv** [comment]
I have removed the package from the official Arch Linux repositories, so I will unsubscribe myself from this ticket.
